# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build:
    desc: "build wasm bin"
    cmds:
      - GOOS=js GOARCH=wasm go build -o web/test.wasm .  
  run:
    desc: build and run player web component
    deps: [build]
    cmds:
      - python -m http.server -d web/
